# CHANGE THIS
fullname: Valerian Hall-Chen
position: Doctoral Candidate
department: Rudolf Peierls Centre for Theoretical Physics / UK Atomic Energy Agency
university: University of Oxford

building: Clarendon Laboratory # optional
street: Parks Road # optional
city: Oxford # optional
postcode: OX1 3PU # optional
country: UK # optional

email: valerian@hall-chen.com
secondary: # optional

formurl: https://formspree.io/myynorgy
url: valerian-chen.github.io/valerian.hall-chen.com

# DON'T CHANGE THIS
collections:
  publications:
  preprints:
